/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * SoundCloud Music Player API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DownloadTrackParams,
  ErrorResponse,
  GetStreamUrlParams,
  HealthStatus,
  ProxyHlsParams,
  ResolveTrackParams,
  SearchResults,
  SearchSoundCloudParams,
  StreamInfo,
  Track,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns server health status
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Search for tracks on SoundCloud
 * @summary Search SoundCloud tracks
 */
export const getSearchSoundCloudUrl = (params: SearchSoundCloudParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/soundcloud/search?${stringifiedParams}`
    : `/api/soundcloud/search`;
};

export const searchSoundCloud = async (
  params: SearchSoundCloudParams,
  options?: RequestInit,
): Promise<SearchResults> => {
  return customFetch<SearchResults>(getSearchSoundCloudUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getSearchSoundCloudQueryKey = (
  params?: SearchSoundCloudParams,
) => {
  return [`/api/soundcloud/search`, ...(params ? [params] : [])] as const;
};

export const getSearchSoundCloudQueryOptions = <
  TData = Awaited<ReturnType<typeof searchSoundCloud>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: SearchSoundCloudParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof searchSoundCloud>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSearchSoundCloudQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchSoundCloud>>
  > = ({ signal }) => searchSoundCloud(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchSoundCloud>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SearchSoundCloudQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchSoundCloud>>
>;
export type SearchSoundCloudQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Search SoundCloud tracks
 */

export function useSearchSoundCloud<
  TData = Awaited<ReturnType<typeof searchSoundCloud>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: SearchSoundCloudParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof searchSoundCloud>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSearchSoundCloudQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Resolves the HLS stream URL for a SoundCloud track
 * @summary Get stream URL for a track
 */
export const getGetStreamUrlUrl = (params: GetStreamUrlParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/soundcloud/stream?${stringifiedParams}`
    : `/api/soundcloud/stream`;
};

export const getStreamUrl = async (
  params: GetStreamUrlParams,
  options?: RequestInit,
): Promise<StreamInfo> => {
  return customFetch<StreamInfo>(getGetStreamUrlUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetStreamUrlQueryKey = (params?: GetStreamUrlParams) => {
  return [`/api/soundcloud/stream`, ...(params ? [params] : [])] as const;
};

export const getGetStreamUrlQueryOptions = <
  TData = Awaited<ReturnType<typeof getStreamUrl>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: GetStreamUrlParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getStreamUrl>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStreamUrlQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStreamUrl>>> = ({
    signal,
  }) => getStreamUrl(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStreamUrl>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetStreamUrlQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStreamUrl>>
>;
export type GetStreamUrlQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get stream URL for a track
 */

export function useGetStreamUrl<
  TData = Awaited<ReturnType<typeof getStreamUrl>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: GetStreamUrlParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getStreamUrl>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStreamUrlQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Resolves a SoundCloud URL to full track metadata
 * @summary Resolve a SoundCloud URL to track info
 */
export const getResolveTrackUrl = (params: ResolveTrackParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/soundcloud/resolve?${stringifiedParams}`
    : `/api/soundcloud/resolve`;
};

export const resolveTrack = async (
  params: ResolveTrackParams,
  options?: RequestInit,
): Promise<Track> => {
  return customFetch<Track>(getResolveTrackUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getResolveTrackQueryKey = (params?: ResolveTrackParams) => {
  return [`/api/soundcloud/resolve`, ...(params ? [params] : [])] as const;
};

export const getResolveTrackQueryOptions = <
  TData = Awaited<ReturnType<typeof resolveTrack>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: ResolveTrackParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof resolveTrack>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getResolveTrackQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof resolveTrack>>> = ({
    signal,
  }) => resolveTrack(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof resolveTrack>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ResolveTrackQueryResult = NonNullable<
  Awaited<ReturnType<typeof resolveTrack>>
>;
export type ResolveTrackQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Resolve a SoundCloud URL to track info
 */

export function useResolveTrack<
  TData = Awaited<ReturnType<typeof resolveTrack>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: ResolveTrackParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof resolveTrack>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getResolveTrackQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Proxies HLS manifest/segment content to bypass CORS restrictions
 * @summary Proxy HLS playlist content
 */
export const getProxyHlsUrl = (params: ProxyHlsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/soundcloud/proxy-hls?${stringifiedParams}`
    : `/api/soundcloud/proxy-hls`;
};

export const proxyHls = async (
  params: ProxyHlsParams,
  options?: RequestInit,
): Promise<Blob> => {
  return customFetch<Blob>(getProxyHlsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getProxyHlsQueryKey = (params?: ProxyHlsParams) => {
  return [`/api/soundcloud/proxy-hls`, ...(params ? [params] : [])] as const;
};

export const getProxyHlsQueryOptions = <
  TData = Awaited<ReturnType<typeof proxyHls>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: ProxyHlsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof proxyHls>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProxyHlsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof proxyHls>>> = ({
    signal,
  }) => proxyHls(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof proxyHls>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ProxyHlsQueryResult = NonNullable<
  Awaited<ReturnType<typeof proxyHls>>
>;
export type ProxyHlsQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Proxy HLS playlist content
 */

export function useProxyHls<
  TData = Awaited<ReturnType<typeof proxyHls>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: ProxyHlsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof proxyHls>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getProxyHlsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Proxy-downloads a SoundCloud track as audio file
 * @summary Download a track
 */
export const getDownloadTrackUrl = (params: DownloadTrackParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/soundcloud/download?${stringifiedParams}`
    : `/api/soundcloud/download`;
};

export const downloadTrack = async (
  params: DownloadTrackParams,
  options?: RequestInit,
): Promise<Blob> => {
  return customFetch<Blob>(getDownloadTrackUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getDownloadTrackQueryKey = (params?: DownloadTrackParams) => {
  return [`/api/soundcloud/download`, ...(params ? [params] : [])] as const;
};

export const getDownloadTrackQueryOptions = <
  TData = Awaited<ReturnType<typeof downloadTrack>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: DownloadTrackParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof downloadTrack>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDownloadTrackQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadTrack>>> = ({
    signal,
  }) => downloadTrack(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof downloadTrack>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DownloadTrackQueryResult = NonNullable<
  Awaited<ReturnType<typeof downloadTrack>>
>;
export type DownloadTrackQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Download a track
 */

export function useDownloadTrack<
  TData = Awaited<ReturnType<typeof downloadTrack>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: DownloadTrackParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof downloadTrack>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getDownloadTrackQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
