/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * SoundCloud Music Player API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Track {
  id: number;
  title: string;
  artist: string;
  duration: number;
  artwork?: string | null;
  permalink_url: string;
  stream_url?: string | null;
  waveform_url?: string | null;
  playback_count?: number | null;
  likes_count?: number | null;
  genre?: string | null;
  description?: string | null;
}

export interface SearchResults {
  tracks: Track[];
  total: number;
  query: string;
}

export interface StreamInfo {
  hls_url?: string | null;
  progressive_url?: string | null;
  track_id: number;
}

export interface ErrorResponse {
  error: string;
  message: string;
}

export type SearchSoundCloudParams = {
  /**
   * Search query
   */
  q: string;
  /**
   * Number of results (default 20)
   */
  limit?: number;
};

export type GetStreamUrlParams = {
  /**
   * SoundCloud track permalink URL
   */
  trackUrl: string;
};

export type ResolveTrackParams = {
  /**
   * SoundCloud URL to resolve
   */
  url: string;
};

export type ProxyHlsParams = {
  /**
   * HLS URL to proxy
   */
  url: string;
};

export type DownloadTrackParams = {
  /**
   * SoundCloud track permalink URL
   */
  trackUrl: string;
  /**
   * Track title for filename
   */
  title?: string;
};
